import {
  black,
  blue100,
  blue200,
  blueGrey500,
  blueGrey700,
  blueGrey800,
  grey300,
  grey500,
  lightBlue900,
  orange400,
  red700,
  transparent,
  tealA700,
  white,
  indigo50,
} from 'material-ui/styles/colors';

const styles = {
  aboutTitle: {
    fontSize: 18,
    marginBottom: 20,
    marginTop: 40,
    opacity: 0.58,
  },
  backArrow: {
    marginBottom: -12,
    marginLeft: -12,
    marginTop: -12,
  },
  card: {
    borderRadius: 5,
    padding: 15,
    width: '100%',
  },
  cardRow: {
    alignItems: 'center',
    display: 'flex',
    flexFlow: 'column',
    marginTop: 10,
  },
  cardTreatment: {
    borderRadius: 5,
    width: '100%',
  },
  checkoutButton: {
    textAlign: 'center',
    width: '100%',
  },
  conditionDescription: {
    fontSize: 15,
    fontWeight: 'lighter',
    textAlign: 'left',
  },
  conditionImg: {
    float: 'right',
    marginTop: 10,
  },
  conditionTitle: {
    alignItems: 'center',
    display: 'flex',
    fontSize: 23,
    fontWeight: 'bold',
    marginBottom: 15,
    marginLeft: 20,
    marginRight: 20,
    textAlign: 'left',
  },
  container: {
    backgroundColor: white,
    height: window.innerHeight - 119,
    marginTop: 15,
    overflow: 'auto',
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
  },
  danger: {
    height: 25,
    marginBottom: 15,
    marginRight: -15,
    marginTop: 15,
    width: 30,
  },
  descriptionTitle: {
    fontSize: 18,
    marginBottom: 10,
    marginTop: 20,
    opacity: 0.58,
  },
  fractureText: {
    textAlign: 'left',
  },
  greenCheck: {
    height: 20,
    marginBottom: 15,
    marginRight: -15,
    marginTop: 15,
    width: 25,
  },
  horizontalContainer: {
    display: 'flex',
    flexDirection: 'row',
    overflow: 'auto',
    padding: 0,
  },
  horizontalLine: {
    borderColor: indigo50,
    borderStyle: 'inset',
    borderWidth: 0.7,
    marginBottom: '1em',
    marginLeft: -15,
    marginRight: -15,
    marginTop: '2em',
  },
  infoImage: {
    float: 'right',
  },
  innerContainer: {
    '@media screen and (min-width: 980px)': /* Desktop */ {
      width: '40%',
    },
    backgroundColor: white,
    justifyContent: 'center',
    margin: '0 auto',
    textAlign: 'center',
    width: '100%',
  },
  play: {
    bottom: 15,
    left: 15,
    position: 'absolute',
  },
  potentialHeader: {
    color: lightBlue900,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    paddingTop: 15,
    width: '95%',
    wordWrap: 'normal',
  },
  potentialInfoContainer: {
    backgroundColor: blue100,
    paddingBottom: 25,
    paddingLeft: 20,
    paddingRight: 20,
  },
  potentialInfoStyle: {
    backgroundColor: blue200,
    borderRadius: 5,
    padding: 10,
  },
  potentialInfoTextStyle: {
    alignItems: 'center',
    color: lightBlue900,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 15,
    marginTop: 10,
    textAlign: 'left',
  },
  prosImage: {
    height: 45,
    marginBottom: 10,
    marginRight: -15,
    marginTop: 5,
    width: 45,
  },
  riskLevel: {
    backgroundColor: tealA700,
    borderRadius: 5,
    color: white,
    display: 'inline',
    fontSize: 12,
    padding: 5,
    textTransform: 'uppercase',
  },
  row: {
    alignItems: 'center',
    display: 'flex',
    marginBottom: 10,
    marginTop: 10,
  },
  sectionContainer: {
    backgroundColor: white,
  },
  sectionContent: {
    lineHeight: 1.3,
    paddingBottom: '1em',
    paddingLeft: '1em',
    paddingRight: '1em',
  },
  sectionHead: {
    backgroundColor: 'white',
    color: black,
    cursor: 'pointer',
    fontSize: 15,
    fontWeight: 700,
    overflow: 'hidden',
    padding: '1em',
    paddingRight: '2.1em',
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    width: '100%',
  },
  step: {
    border: '1px solid transparent',
    borderColor: grey300,
    borderRadius: 5,
    margin: 5,
    padding: 10,
    textAlign: 'center',
  },
  stepsTitle: {
    color: blueGrey700,
    display: 'flex',
    fontSize: 18,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 15,
  },
  tab: {
    color: blueGrey800,
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  tabSelected: {
    color: red700,
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  tabbarInk: {
    background: transparent,
    height: 0,
  },
  tableImageColumn: {
    paddingLeft: 0,
    paddingRight: 0,
    width: 50,
  },
  tableNameColumn: {
    paddingLeft: 0,
    paddingRight: 0,
  },
  tableNameInfoColumn: {
    height: 24,
    paddingLeft: 0,
    paddingRight: 0,
    width: 45,
  },
  tableRow: {
    borderBottom: 'none',
  },
  talkButton: {
    backgroundColor: orange400,
    borderRadius: 20,
    color: white,
    fontSize: 18,
    marginTop: 20,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
  },
  textReason: {
    color: black,
    fontSize: 16,
    marginBottom: 3,
    opacity: 0.65,
    whiteSpace: 'normal',
    width: '100%',
    wordWrap: 'break-word',
  },
  thumbnailContainer: {
    marginBottom: 20,
    marginTop: 20,
    position: 'relative',
  },
  thumbnailImage: {
    borderRadius: 5,
    height: 200,
    margin: 5,
    width: '98%',
  },
  titleText: {
    fontFamily: 'Roboto',
    fontSize: 16,
  },
  toggleButton: {
    marginRight: 10,
    marginTop: 10,
  },
  treatmentContainer: {
    marginBottom: 10,
    marginTop: 10,
  },
  treatmentDescription: {
    color: blueGrey500,
    fontSize: 15,
    marginLeft: 5,
    textAlign: 'left',
    whiteSpace: 'normal',
    wordWrap: 'break-word',
  },
  treatmentInnerRow: {
    border: '1px solid transparent',
    borderColor: grey500,
    borderRadius: 5,
    color: black,
    fontSize: 14,
    fontWeight: 'bold',
    margin: 5,
    maxWidth: 120,
    minWidth: 120,
    padding: 10,
    textAlign: 'center',
  },
  treatmentProcedureText: {
    color: lightBlue900,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    marginLeft: 5,
    paddingTop: 20,
    textAlign: 'left',
    width: '100%',
  },
  treatmentRow: {
    marginBottom: -8,
    overflow: 'auto',
  },
  treatmentSeparator: {
    border: '2px solid #bbdefb',
    marginLeft: 20,
    width: '10%',
  },
  treatmentTitle: {
    color: black,
    fontSize: 20,
    marginBottom: 5,
    marginTop: 10,
  },
  valuePointText: {
    color: lightBlue900,
    fontSize: 14,
    fontWeight: 'bold',
    paddingLeft: 15,
    paddingRight: 15,
    width: 100,
  },
  video: {
    marginBottom: 20,
  },
  videoContainer: {
    display: 'flex',
    justifyContent: 'center',
  },
  viewTreatment: {
    color: blue200,
    display: 'flex',
    fontSize: 15,
  },
};

export default styles;
